// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkOi2xOtyyDUt2rCEA68xdXG3dxp_DZk',
    appId: '1:511336665354:web:3aa7fc7be2a3b54a2f6af3',
    messagingSenderId: '511336665354',
    projectId: 'americano-cruz',
    authDomain: 'americano-cruz.firebaseapp.com',
    storageBucket: 'americano-cruz.firebasestorage.app',
    measurementId: 'G-L4XGYZCEQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApo33SDnlL89qAHg5PB8dsZG-NdYFFv88',
    appId: '1:511336665354:android:03af4e517b7a2e3c2f6af3',
    messagingSenderId: '511336665354',
    projectId: 'americano-cruz',
    storageBucket: 'americano-cruz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXlG4qD2T9oIjfqNHXYAHhfdm3i1345s',
    appId: '1:511336665354:ios:e40b711ade85ffe22f6af3',
    messagingSenderId: '511336665354',
    projectId: 'americano-cruz',
    storageBucket: 'americano-cruz.firebasestorage.app',
    iosBundleId: 'com.codecats.americanocruz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXXlG4qD2T9oIjfqNHXYAHhfdm3i1345s',
    appId: '1:511336665354:ios:e40b711ade85ffe22f6af3',
    messagingSenderId: '511336665354',
    projectId: 'americano-cruz',
    storageBucket: 'americano-cruz.firebasestorage.app',
    iosBundleId: 'com.codecats.americanocruz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXkOi2xOtyyDUt2rCEA68xdXG3dxp_DZk',
    appId: '1:511336665354:web:5220fde98e87981e2f6af3',
    messagingSenderId: '511336665354',
    projectId: 'americano-cruz',
    authDomain: 'americano-cruz.firebaseapp.com',
    storageBucket: 'americano-cruz.firebasestorage.app',
    measurementId: 'G-847DNKG0ZG',
  );

}